/** French editorial copy. Brand names, code samples, and project filenames stay unchanged. */
export const frenchCopy: Record<string, string> = {
  Process: "Comment ça marche",
  Features: "Fonctionnalités",
  Pricing: "Tarifs",
  FAQ: "FAQ",
  Dashboard: "Tableau de bord",
  "Log in": "Se connecter",
  "Clonyfy home": "Accueil Clonyfy",
  "Open menu": "Ouvrir le menu",
  "Close menu": "Fermer le menu",
  "Get Instant Access": "Commencer maintenant",
  "Get instant access": "Commencer maintenant",
  "See it.": "Voyez-le.",
  "Clone it.": "Clonez-le.",
  "Make it yours.": "Faites-en le vôtre.",
  "Trusted by ambitious creators.": "Adopté par les créateurs.",
  "Built for what comes next.": "Pour vos prochaines idées.",
  "View portrait": "Voir le portrait",
  "Close portrait": "Fermer le portrait",
  Portrait: "Portrait",
  "Clone any website with AI in seconds. Turn a URL into a pixel-perfect, fully editable starting point. No design or coding skills required.":
    "Clonez n’importe quel site en quelques secondes grâce à l’IA. Une simple URL devient une base fidèle à l’original, entièrement personnalisable. Aucune compétence en design ou en code nécessaire.",
  "See how it works": "Voir comment ça marche",
  "Website URL to clone": "Adresse du site à cloner",
  "Paste a website URL": "Collez une URL",
  "Try it": "Essayer",
  "Enter a website URL, like example.com.":
    "Saisissez l’adresse d’un site, par exemple exemple.fr.",
  "01 / LESS EXCUSES. MORE POSSIBILITIES.": "01 / MOINS DE FREINS. PLUS DE POSSIBILITÉS.",
  "I can't afford a developer": "Pas de budget pour un développeur",
  "I saw the perfect website": "J’ai trouvé le site idéal",
  "Builders are too limiting": "Les éditeurs sont trop limités",
  "I don't have time to learn": "Pas le temps de tout apprendre",
  "Design isn't my thing": "Le design, ce n’est pas mon truc",
  "Freelancers are too slow": "Les délais sont trop longs",
  "You don't need excuses.": "Plus rien ne vous retient.",
  "You need Clonyfy.": "Passez à Clonyfy.",
  "We are not building a website builder. We are building a website production accelerator that integrates into existing workflows and reduces site creation from days to minutes.":
    "Clonyfy accélère la création de vos sites et s’intègre à votre façon de travailler. Partez d’une base concrète et passez de l’idée au résultat en quelques minutes au lieu de plusieurs jours.",
  "GET YOURS FOR JUST $19.99 ↗": "DÈS 19,99 $US PAR MOIS ↗",
  "Clonyfy in numbers": "Clonyfy en chiffres",
  "A LITTLE PROOF. A LOT OF POSSIBILITY.": "DES RÉSULTATS QUI PARLENT D’EUX-MÊMES.",
  "Websites cloned with Clonyfy": "Sites clonés avec Clonyfy",
  "Avg. clone time": "Temps moyen",
  "Accuracy rate": "Fidélité",
  "Active Users": "Utilisateurs actifs",
  "User Rating": "Note des utilisateurs",
  "2min": "2 min",
  "99.2%": "99,2 %",
  "+9,000": "+9 000",
  "4.9/5": "4,9/5",
  "02 / A BETTER STARTING POINT": "02 / PARTEZ SUR DE BONNES BASES",
  "Stop doing it": "Simplifiez-vous",
  "the hard way.": "la création.",
  "Traditional way": "Sans Clonyfy",
  "The Clonyfy way": "Avec Clonyfy",
  "Paying thousands for a website": "Dépenser des milliers pour un site",
  "Spending weeks rebuilding something that already exists":
    "Passer des semaines à refaire ce qui existe déjà",
  "Learning design just to launch a product": "Apprendre le design juste pour lancer son projet",
  "Waiting on a freelancer who delivers late and over budget":
    "Subir les retards et les dépassements de budget",
  "Starting from a blank page every single time": "Repartir de zéro à chaque projet",
  "Clone any site in 2 minutes, full code, yours forever":
    "Clonez un site en 2 minutes, avec tout son code, à vous pour toujours",
  "Redesign it visually, no coding required": "Personnalisez-le visuellement, sans coder",
  "Export to Figma, ZIP, or deploy directly": "Exportez vers Figma, en ZIP, ou publiez directement",
  "Launch today, not next month": "Lancez-vous dès aujourd’hui",
  "Complete code ownership, no lock-in":
    "Gardez la maîtrise de votre code, sans dépendre d’une plateforme",
  "Online Hustlers": "Entrepreneurs du web",
  Developers: "Développeurs",
  Agencies: "Agences",
  "See a site that works. Clone it, make it yours, launch it today.":
    "Un site vous inspire ? Clonez-le, adaptez-le à votre image et lancez-vous aujourd’hui.",
  "Speed up frontend development and skip repetitive rebuilds.":
    "Accélérez le développement front-end et évitez les tâches répétitives.",
  "Deliver client websites faster and increase margins.":
    "Livrez les sites de vos clients plus vite et améliorez vos marges.",
  "REBUILD FROM ZERO": "REPARTIR DE ZÉRO",
  "7 DAYS": "7 JOURS",
  "START WITH CLONYFY": "DÉMARRER AVEC CLONYFY",
  "2 MIN.": "2 MIN.",
  "LESS FRICTION. MORE FORWARD.": "MOINS D’OBSTACLES. PLUS D’ÉLAN.",
  "03 / THE PROCESS": "03 / COMMENT ÇA MARCHE",
  "An idea. A URL.": "Une idée. Une URL.",
  "A head start.": "Une longueur d’avance.",
  "See the cloning process in action.": "Découvrez le clonage en action.",
  "From raw URL to production-ready React component in under two minutes.":
    "D’une simple URL à un composant React prêt à l’emploi, en moins de deux minutes.",
  "Explore the cloning process": "Découvrez les étapes du clonage",
  "Paste any URL": "Collez une URL",
  "Input any public website URL to start. Clonyfy will analyze the structure.":
    "Collez l’adresse d’un site public. Clonyfy en analyse la structure.",
  "AI parsing & cloning": "L’IA analyse et clone",
  "Our Vision AI crawls the assets and structures the React components.":
    "Notre IA visuelle récupère les éléments du site et les organise en composants React.",
  "Redesign in browser": "Personnalisez en direct",
  "Click any text, image, or section to edit visually. Code updates instantly.":
    "Modifiez les textes, les images ou les sections en un clic. Le code se met à jour instantanément.",
  "1-Click deploy": "Publiez en un clic",
  "Export as React + Tailwind code, Figma file, or deploy directly to Vercel.":
    "Exportez le code React + Tailwind, un fichier Figma ou publiez directement sur Vercel.",
  "A starting point. Not a blank page.": "Une vraie base pour démarrer.",
  "Every detail, understood.": "Chaque détail est pris en compte.",
  "Their inspiration. Your expression.": "L’inspiration devient votre création.",
  "All yours. Ready for the world.": "Votre projet, prêt à être publié.",
  "FOUR STEPS. INFINITE POSSIBILITIES.": "QUATRE ÉTAPES. TOUT DEVIENT POSSIBLE.",
  "THE CLONYFY WORKSPACE": "L’ESPACE CLONYFY",
  STEP: "ÉTAPE",
  "READY TO CLONE": "PRÊT À CLONER",
  "A public website. A world of possibilities.": "Un site public. Tout un monde de possibilités.",
  "EXTRACTED ✓": "EXTRAIT ✓",
  "TRY A DIFFERENT DIRECTION": "ESSAYEZ UN AUTRE STYLE",
  "Restore original": "Rétablir l’original",
  "Invert the canvas": "Inverser les couleurs",
  "An editable design. With the code to match.":
    "Un design personnalisable et le code qui va avec.",
  "forma / ready to ship": "forma / prêt à publier",
  "Your code leaves with you. Always.": "Votre code vous appartient. Pour toujours.",
  "EXPLORE THE INTERACTIVE DEMO": "TESTEZ LA DÉMO INTERACTIVE",
  "BUILT FROM POSSIBILITY": "DONNEZ VIE À VOS IDÉES",
  "04 / YOUR UNFAIR ADVANTAGE": "04 / VOTRE LONGUEUR D’AVANCE",
  "Everything you need.": "Tout ce qu’il vous faut.",
  "Nothing you don't.": "Rien de superflu.",
  "The distance between a great reference and your next great project just got smaller.":
    "Transformez plus vite vos meilleures inspirations en projets concrets.",
  Speed: "Rapidité",
  "2 min cloning": "Clonage en 2 minutes",
  "Distributed AI pipeline processes even complex sites in about 2 minutes.":
    "Notre infrastructure d’IA traite même les sites complexes en environ deux minutes.",
  Code: "Code",
  "Clean code output": "Du code propre et structuré",
  "Export semantic React + Tailwind components. Production-ready architecture.":
    "Exportez des composants React + Tailwind bien structurés, avec une architecture prête pour la production.",
  Editor: "Éditeur",
  "Visual editor": "Éditeur visuel",
  "Click any element to edit text, colors, spacing or layout. Pixel-level precision.":
    "Modifiez les textes, les couleurs, les espacements et la mise en page, au pixel près.",
  Design: "Design",
  "Figma export": "Export vers Figma",
  "Convert any website into editable Figma designs.":
    "Transformez n’importe quel site en maquettes Figma modifiables.",
  DevOps: "DevOps",
  "GitHub integration": "Intégration GitHub",
  "Push clones directly to a repo. Commit history, branches, and PRs built in.":
    "Envoyez vos sites clonés vers un dépôt GitHub. Historique des commits, branches et pull requests sont intégrés.",
  Security: "Sécurité",
  "Privacy-first": "La confidentialité avant tout",
  "We never store your website content beyond your session. SOC 2 Type II.":
    "Le contenu de votre site n’est jamais conservé au-delà de votre session. SOC 2 Type II.",
  Scale: "Volume",
  "Multi-page cloning": "Clonage de sites complets",
  "Clone entire site structures — linked pages, shared layouts — all in one pass.":
    "Clonez toute la structure d’un site en une seule fois : pages liées et mises en page communes incluses.",
  "05 / OWN EVERY PIXEL": "05 / CHAQUE PIXEL VOUS APPARTIENT",
  "Your code.": "Votre code.",
  "Your rules.": "Vos règles.",
  "Zero dependencies. Total freedom.": "Aucune contrainte. Une liberté totale.",
  "Export your project as a clean ZIP, push it to GitHub, or deploy instantly to Vercel, Netlify, or any host you want. No lock-in, no restrictions. If you ever decide to leave, your code leaves with you, fully yours, forever.":
    "Exportez votre projet en ZIP, envoyez-le sur GitHub ou publiez-le sur Vercel, Netlify ou l’hébergeur de votre choix. Vous restez libre de changer d’outil à tout moment. Votre code vous appartient, pour toujours.",
  "EXPORT ANYWHERE": "EXPORTEZ OÙ VOUS VOULEZ",
  "NO LOCK-IN ↗": "EN TOUTE LIBERTÉ ↗",
  "YOUR WORKSPACE": "VOTRE ESPACE",
  "THE WORLD": "LE MONDE",
  "06 / WHAT YOU ACTUALLY GAIN": "06 / CE QUE VOUS Y GAGNEZ",
  "Start from reality.": "Partez du concret.",
  "We don't help you start from scratch.": "Ne repartez plus de zéro.",
  "We help you start from reality.": "Appuyez-vous sur ce qui fonctionne.",
  "The fastest way to rebuild, redesign & ship any website.":
    "Le moyen le plus rapide de recréer, personnaliser et publier un site.",
  "+7 Days → 2 Minutes.": "+7 jours → 2 minutes.",
  "Stop rebuilding what already exists. Clone it, adapt it, ship it.":
    "Ne refaites plus ce qui existe déjà. Clonez, adaptez, publiez.",
  "Edit without coding.": "Modifiez sans coder.",
  "The visual editor lets you modify any page directly in the browser.":
    "L’éditeur visuel vous permet de modifier chaque page directement dans le navigateur.",
  "Figma file included.": "Fichier Figma inclus.",
  "Every clone generates a ready-to-share Figma file.":
    "Chaque site cloné génère un fichier Figma prêt à être partagé.",
  "Deploy in 1 click.": "Publiez en un clic.",
  "Next.js 14, Dockerfile included. Vercel, Netlify, Railway, your own VPS — ready to ship in 2 minutes.":
    "Next.js 14 et Dockerfile inclus. Vercel, Netlify, Railway ou votre propre VPS : prêt à publier en deux minutes.",
  "From over seven days to two minutes": "De plus de sept jours à deux minutes",
  "7 days": "7 jours",
  "2 min.": "2 min.",
  "07 / FOR PEOPLE IN MOTION": "07 / POUR CEUX QUI PASSENT À L’ACTION",
  "Built for people": "Pour ceux qui",
  "who ship.": "concrétisent leurs idées.",
  "Start Cloning": "Cloner un site",
  "Clone a client's inspiration site in seconds. Redesign it, export clean code, deliver faster than your competitors quote.":
    "Clonez le site qui inspire votre client en quelques secondes. Adaptez-le, exportez un code propre et livrez avant même que vos concurrents aient envoyé leur devis.",
  Freelancers: "Indépendants",
  "Stop rebuilding from scratch. Clone the structure, make it yours, ship it tonight.":
    "Ne repartez plus de zéro. Clonez la structure, personnalisez-la et livrez dès ce soir.",
  "Online Entrepreneurs": "Entrepreneurs du web",
  "See a site that converts. Clone the layout, swap the content, launch your offer.":
    "Repérez un site qui convertit. Reprenez sa mise en page, ajoutez votre contenu et lancez votre offre.",
  "08 / IN GOOD COMPANY": "08 / VOUS ÊTES EN BONNE COMPAGNIE",
  "Loved by builders": "Ils créent avec Clonyfy.",
  "everywhere.": "Partout dans le monde.",
  "9,000+ developers and designers trust Clonyfy for rapid prototyping and production deployments.":
    "Plus de 9 000 développeurs et designers font confiance à Clonyfy pour créer leurs prototypes et mettre leurs sites en ligne plus rapidement.",
  "4.9 / 5 USER RATING": "4,9 / 5 — NOTE DES UTILISATEURS",
  "Previous testimonial": "Témoignage précédent",
  "Next testimonial": "Témoignage suivant",
  "Clonyfy saved us 3 weeks of work. We cloned a competitor's pricing page, tweaked it to match our brand, and shipped the same day. Insane ROI.":
    "Clonyfy nous a fait gagner trois semaines de travail. Nous avons cloné la page de tarifs d’un concurrent, adapté le design à notre marque et publié le jour même. Le retour sur investissement est impressionnant.",
  "The code output is actually clean. I was expecting messy div soup but it exports proper components with Tailwind. I'd write it similarly myself.":
    "Le code généré est vraiment propre. Je m’attendais à un empilement de div, mais on obtient de vrais composants Tailwind bien structurés. C’est très proche de ce que j’aurais écrit moi-même.",
  "As a freelancer, I quote clients on day one and deliver prototypes the same afternoon. Clonyfy is essentially a second developer on my team.":
    "En freelance, j’envoie le devis le matin et je livre le prototype l’après-midi. Avec Clonyfy, c’est comme si j’avais un deuxième développeur à mes côtés.",
  "We use it to build rapid reference designs before sprints. Cloning existing great UIs as a starting point is way faster than building from scratch.":
    "Nous l’utilisons pour préparer rapidement des maquettes de référence avant nos sprints. Partir d’une belle interface existante fait gagner un temps fou.",
  "The AI redesign mode is what keeps me here. I clone a site, then tell it 'make it more minimalist'. It just works every single time.":
    "C’est la personnalisation par IA qui m’a convaincue. Je clone un site, puis je demande un style plus minimaliste. Le résultat est au rendez-vous à chaque fois.",
  "Setup was zero. Paste URL, wait 7 seconds, done. No API keys, no config. The competition takes 10 steps just to get started.":
    "Rien à installer. On colle une URL, on attend sept secondes et c’est prêt. Pas de clé API, pas de configuration. Ailleurs, il faut déjà dix étapes pour démarrer.",
  "We replaced our entire prototyping workflow with Clonyfy. The visual editor alone is worth the subscription. Super polished tool.":
    "Nous avons remplacé tout notre processus de prototypage par Clonyfy. L’éditeur visuel justifie à lui seul l’abonnement. L’outil est vraiment abouti.",
  "Exported clean Next.js code on first try. I just had to swap in our actual data and it was basically production-ready. Wild.":
    "Du code Next.js propre dès le premier export. J’ai simplement ajouté nos données et le projet était quasiment prêt pour la production. Bluffant.",
  "Head of Growth, Orbit SaaS": "Responsable croissance, Orbit SaaS",
  "Senior Engineer, Liftoff": "Ingénieur senior, Liftoff",
  "Freelance Product Designer": "Designer produit indépendante",
  "Design Lead, Cascade": "Responsable design, Cascade",
  "Product Manager, Synthex": "Cheffe de produit, Synthex",
  "CTO, Refract": "Directeur technique, Refract",
  "UX Director, Cloudform": "Directrice UX, Cloudform",
  "Fullstack Dev, Stackflow": "Développeur full-stack, Stackflow",
  "09 / AN INVESTMENT IN MOMENTUM": "09 / INVESTISSEZ DANS VOTRE ÉLAN",
  "Cheaper than a": "Moins qu’une heure",
  "developer's hour.": "de développement.",
  "Billing period": "Période de facturation",
  Monthly: "Mensuel",
  Yearly: "Annuel",
  "20% less with yearly billing.": "Économisez 20 % avec l’abonnement annuel.",
  "/ YOUR NEXT CHAPTER": "/ VOTRE PROCHAINE ÉTAPE",
  "Most popular": "Le plus choisi",
  Starter: "Starter",
  Growth: "Growth",
  "≈ 1 coffee per week": "≈ un café par semaine",
  "For testing on real projects before committing.":
    "Pour tester Clonyfy sur vos premiers projets.",
  "For growing teams shipping faster every week.":
    "Pour les équipes qui créent toujours plus vite.",
  "For high-volume cloning with priority support.":
    "Pour cloner à grande échelle avec une assistance prioritaire.",
  "Get started": "Commencer",
  "Start now": "Commencer maintenant",
  "10 Website Clones / Month": "10 sites clonés par mois",
  "25 Website Clones / Month": "25 sites clonés par mois",
  "Unlimited Website Clones": "Clonage de sites illimité",
  "Unlimited Screens": "Écrans illimités",
  "Code & ZIP Export": "Export du code et en ZIP",
  "Visual Builder & Editor": "Création et édition visuelles",
  "6 Days/Week Support": "Assistance 6 jours sur 7",
  "7 Days/Week Priority Support": "Assistance prioritaire 7 jours sur 7",
  "Cancel Anytime": "Résiliation à tout moment",
  "Figma Export": "Export Figma",
  "Access to Templates": "Accès aux modèles",
  "API Access": "Accès à l’API",
  "Billed monthly. Cancel anytime.": "Facturation mensuelle. Résiliation à tout moment.",
  "/mo": "/mois",
  "$2,000+ average dev cost for one site.":
    "Un site coûte en moyenne plus de 2 000 $US à développer.",
  "YOURS IN MINUTES. YOURS TO KEEP. ↗": "PRÊT EN QUELQUES MINUTES. À VOUS POUR TOUJOURS. ↗",
  "10 / GOOD QUESTIONS": "10 / VOS QUESTIONS",
  "Everything you": "Tout ce que vous",
  "want to know.": "voulez savoir.",
  "Can't find the answer?": "Vous avez une autre question ?",
  "Reach out to our": "Contactez notre",
  "support team ↗": "équipe d’assistance ↗",
  "Is it legal to clone websites?": "Est-il légal de cloner un site web ?",
  "CLONYFY is designed for legitimate use cases: prototyping, client pitches, competitive analysis, archival, and reference implementations. You are responsible for complying with each website's terms of service. We enforce robots.txt by default and never crawl at disruptive rates. Always ensure you have permission to capture and use a site's content.":
    "Clonyfy est conçu pour des usages légitimes : prototypage, présentations clients, analyse concurrentielle, archivage et création de références. Vous devez respecter les conditions d’utilisation de chaque site. Nous appliquons les règles de robots.txt par défaut et limitons les requêtes pour ne pas perturber les sites. Assurez-vous toujours d’avoir l’autorisation de capturer et d’utiliser leur contenu.",
  "What kinds of sites work best?": "Quels types de sites donnent les meilleurs résultats ?",
  "Marketing sites, landing pages, portfolios, documentation and SaaS pages clone with the highest fidelity. Heavily gated apps or canvas-driven experiences are partially supported.":
    "Les sites vitrines, pages de vente, portfolios, documentations et sites SaaS offrent les meilleurs résultats. Les applications dont l’accès est très restreint ou qui reposent sur un canvas ne sont que partiellement prises en charge.",
  "How long does cloning take?": "Combien de temps prend le clonage ?",
  "Most sites finish in about two minutes. Simple pages are done in seconds; large multi-page structures take a little longer while linked pages and shared layouts are processed in one pass.":
    "La plupart des sites sont clonés en environ deux minutes. Une page simple peut être prête en quelques secondes. Les sites volumineux prennent un peu plus de temps, car les pages liées et les mises en page communes sont traitées ensemble.",
  "Can I deploy the generated project to Vercel?": "Puis-je publier le projet généré sur Vercel ?",
  "Yes. Export as a clean ZIP, push straight to GitHub, or deploy in one click to Vercel, Netlify, Railway or your own VPS. A Dockerfile is included.":
    "Oui. Exportez votre projet en ZIP, envoyez-le sur GitHub ou publiez-le en un clic sur Vercel, Netlify, Railway ou votre propre VPS. Un Dockerfile est inclus.",
  "Do you store the captured pages on your servers?":
    "Conservez-vous les pages capturées sur vos serveurs ?",
  "No. We never store your website content beyond your session. Clonyfy is SOC 2 Type II with AES-256 encryption, zero logs and GDPR compliance.":
    "Non. Le contenu de votre site n’est jamais conservé au-delà de votre session. Clonyfy est conforme à SOC 2 Type II et au RGPD, utilise le chiffrement AES-256 et ne conserve aucun journal d’activité.",
  "11 / THE NEXT MOVE IS YOURS": "11 / À VOUS DE JOUER",
  "Stop thinking.": "Passez à l’action.",
  "Build what works.": "Créez ce qui marche.",
  "Join +9000 entrepreneurs.": "Rejoignez plus de 9 000 entrepreneurs.",
  "Your next great project starts with a URL.": "Votre prochain projet commence par une URL.",
  Product: "Produit",
  Company: "Entreprise",
  Support: "Assistance",
  Privacy: "Confidentialité",
  Terms: "Conditions",
  Account: "Compte",
  "Create account": "Créer un compte",
  "We don't help you start from scratch. We help you start from reality.":
    "Ne repartez plus de zéro. Appuyez-vous sur ce qui fonctionne.",
  "(opens in a new tab)": "(s’ouvre dans un nouvel onglet)",
  "Clonyfy. All rights reserved.": "Clonyfy. Tous droits réservés.",
  "Built for people who ship.": "Pour ceux qui concrétisent leurs idées.",
  "Back to site": "Retour au site",
  "A better starting point": "Un temps d’avance",
  "Good ideas deserve": "Les belles idées méritent",
  "a head start.": "une longueur d’avance.",
  "A spark of inspiration. A space to make it yours.":
    "Une étincelle d’inspiration. Un espace pour lui donner vie.",
  "Your creative space": "Votre espace créatif",
  "or continue with email": "ou avec votre e-mail",
  "Your name": "Votre nom",
  "you@example.com": "vous@exemple.fr",
  "Show password": "Afficher le mot de passe",
  "Hide password": "Masquer le mot de passe",
  "Make something that’s yours.": "Créez ce qui vous ressemble.",
  "Full name": "Nom complet",
  "Email address": "Adresse e-mail",
  Password: "Mot de passe",
  or: "ou",
  "Welcome back.": "Heureux de vous revoir.",
  "Log in to keep cloning, redesigning and shipping.":
    "Connectez-vous pour retrouver vos projets et continuer à créer.",
  "New to Clonyfy?": "Vous découvrez Clonyfy ?",
  "Create an account": "Créer un compte",
  "Create your account and clone your first site in under two minutes.":
    "Créez votre compte et clonez votre premier site en moins de deux minutes.",
  "Already have an account?": "Vous avez déjà un compte ?",
  "LET’S TALK ↗": "PARLONS-EN ↗",
  "INDEPENDENT DESIGN STUDIO": "STUDIO DE DESIGN INDÉPENDANT",
  "Objects.": "Des objets.",
  "With a": "Un autre",
  "point of view.": "regard.",
  "Discover the collection": "Découvrir la collection",
  "FORM MEETS FEELING.": "LA FORME RENCONTRE L’ÉMOTION.",
  "01 / THE INSPIRATION": "01 / L’INSPIRATION",
  "forma / your workspace": "forma / votre espace",
  EDITABLE: "MODIFIABLE",
  "Yours to make your own. ↗": "À vous de le personnaliser. ↗",
  "Good design. Your next starting point.": "Un beau design. Le début de votre projet.",
  "Structure captured. Possibilities unlocked.": "La structure est prête. À vous de créer.",
  CAPTURE: "CAPTURE",
  ANALYZE: "ANALYSE",
  STRUCTURE: "STRUCTURE",
  READY: "PRÊT",
  "MAKE IT YOURS ↗": "PERSONNALISEZ ↗",
  "DESIGN PROPERTIES": "PROPRIÉTÉS DU DESIGN",
  Radius: "Arrondi",
  Spacing: "Espacement",
  Color: "Couleur",
  "LAYERS. VECTORS. FULLY EDITABLE.": "CALQUES. VECTEURS. TOUT EST MODIFIABLE.",
  "merge & ship": "fusionner et publier",
  "CHANGES COMMITTED ✓": "MODIFICATIONS VALIDÉES ✓",
  "YOUR CONTENT. YOUR CONTROL.": "VOTRE CONTENU. VOTRE CONTRÔLE.",
  "/ HOME": "/ ACCUEIL",
  "ZIP / CODE": "ZIP / CODE",
  "Page not found": "Page introuvable",
  "The page you're looking for doesn't exist or has been moved.":
    "La page que vous cherchez n’existe pas ou a été déplacée.",
  "Go home": "Retour à l’accueil",
  "This page didn't load": "Cette page n’a pas pu se charger",
  "Something went wrong on our end. You can try refreshing or head back home.":
    "Un problème est survenu. Réessayez ou revenez à l’accueil.",
  "Try again": "Réessayer",
};
